Revamp mirrord buttons
metalbear-co/mirrord-vscode pull request #13
Opened 2023-06-27 09:29 UTC by DmitryDodzin

Change status bar buttons to be more clear on what they do with minimal footprint

2023-06-28 10:45 UTC, Razz4780 approved these changes
Looks stunning ^^

Noticed some quirks aroud `contributions` entry in `package.json` - settings command is never shown, but I guess it's out of scope

2023-06-28 12:20 UTC, Razz4780 commented
Actually, the feedback link shows the homepage (https://mirrord.dev/feedback). Probably not what we want

2023-06-28 15:04 UTC, eyalb181 requested changes
The menu takes a really long time to show up when hovering - it's essentially an easter egg. Is there a way to make the menu show up faster?

2023-07-03 10:18 UTC, Razz4780 commented
> The menu takes a really long time to show up when hovering - it's essentially an easter egg. Is there a way to make the menu show up faster?

Couldn't find anything in the VS Code API. Also, this is something the user can set in their preferences. Probably out of our control

2023-07-03 11:50 UTC, eyalb181 approved these changes

2023-07-04 10:51 UTC, eyalb181 requested changes

2023-07-04 10:51 UTC, eyalb181 commented on src/status.ts
> +        statusBar.tooltip.appendMarkdown(`\n\n[Teams Waitlist](command:${waitlistCommandId})`);
```suggestion
        statusBar.tooltip.appendMarkdown(`\n\n[mirrord for Teams Waitlist](command:${waitlistCommandId})`);
```

2023-07-04 11:15 UTC, eyalb181 approved these changes

2023-07-04 12:29 UTC, merged