Change verify config action to pass --ide, changing some target related errors to warnings.
metalbear-co/mirrord-vscode pull request #71
Opened 2023-10-02 20:00 UTC by meowjesty

- Issue: ...

(wip)

2023-10-03 04:27 UTC, infiniteregrets requested changes
the tests should not pass for this, this quite weird - we donot have a release in mirrord to be able to run with --ide

i believe the command fails but you dont fail in the extension, so a bug

2023-10-03 20:20 UTC, meowjesty commented
> the tests should not pass for this, this quite weird - we donot have a release in mirrord to be able to run with --ide
i believe the command fails but you dont fail in the extension, so a bug

vscode extension behavior is that uncaught exceptions just silently make the whole thing stop, no errors bubble up or anything. Added a `try/catch` block around the main function to prevent this from ever happening again.

2023-10-05 05:09 UTC, infiniteregrets approved these changes

2023-10-05 07:13 UTC, t4lz requested changes

2023-10-05 07:13 UTC, t4lz commented on src/api.ts
> +      const args = ['verify-config', '--ide', '--path', `${configPath.path}`];
We're reverting the addition of the `--path` arg, the extension shouldn't use it.

2023-10-06 08:34 UTC, t4lz approved these changes

2023-10-06 08:39 UTC, merged